<?php



/**
 * Skeleton subclass for performing query and update operations on the 'devices' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Fri May 24 02:10:25 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class DevicesQuery extends BaseDevicesQuery
{
}
